### PR TITLE
Make juniper master work

### PR DESCRIPTION
**Pull request by LegNeato**

### CODE REVIEW

**Comment by divy-work** [comment]
@LegNeato Thank you so much for the PR! I actually got it working :smile: (Thanks to you)
Also, benchmarks are now working! TYSM! Do you think I can close this PR as it is already implemented?

**Comment by LegNeato** [comment]
Yay, I'm glad it is working! I'll close if you don't need it 😃 . Would love to see some benchmarks posted! We have only done microbenchmarks on juniper itself, on my TODO to really stress it.

**Comment by LegNeato** [comment]
(note if you rely on `juniper_actix` a lot of boiler plate and gnarly generics in your project goes away)

**Comment by LegNeato** [comment]
My PR also shows you how to use `EmptySubscription` so you don't need a fake hello world one.

**Comment by divy-work** [comment]
Thanks :smile:. I'll ping you at https://github.com/graphql-rust/juniper/issues/690 with the benchmarks.

**Comment by divy-work** [comment]
@LegNeato Can you do the PR with the EmptySubscription? I think we need that

**Pull request closed without merging**
